title: Between One and Zero
description: A cybersecurity blog about defense with an attacker mindset
url: "https://yaronking.com"
baseurl: ""
markdown: kramdown
highlighter: rouge
theme: null
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"